# fly.toml app configuration file generated for logbook-backend on 2025-08-13T08:10:44+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'clean-ai-starter'
primary_region = 'sjc'

[build]
  dockerfile = 'src/main/docker/Dockerfile.jvm'

[env]
  QUARKUS_HTTP_HOST = "0.0.0.0"
  QUARKUS_HTTP_PORT = "8080"
  QUARKUS_FLYWAY_MIGRATE_AT_START = "true"
  QUARKUS_PROFILE = "main"
  APP_STORAGE_S3_BUCKET = "clean-ai-starter-bucket-main"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/q/health"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
